[project]
name = "oracle-vector-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain-community>=0.3.27",
    "langchain-openai>=0.3.30",
    "mcp[cli]>=1.12.4",
    "oracledb>=3.3.0",
]
